### PR TITLE
both article status as well as doi/pii identifiers added to the article.php

### PR DESCRIPTION
**Pull request by SiggiSmara**
replaces #5  and partially #6 (the doi/pii part, not the pubyear part, haven't run into that problem myself).

### CODE REVIEW

**Comment by tmpjr** [comment]
Is this now resolved? Can I close this request? I merged the other related request.

**Comment by SiggiSmara** [comment]
I would say that is up to you to decide. What is new in this one that is not in #6 is the pub status plus the doi and pii are found via the normal xml way rather than the regex matching from @sujliu. I personally think that the xml way is more readable and I have not yet seen a failure of that implementation. But @sujliu might have other cases where the regex matching they propose does a better job.

If you are happy with the way the doi and the pii are dealt with in #6 then I can also sync back from the last merge and make another pull request only with the pub status. Or if the pub status is not something you would want to add then you can just close this one and that will be the end of it. It's up to you.

..

**Comment by tmpjr** [comment]
Thanks, @SiggiSmara. If you can, please redo this request based on the latest master to make it easier on me doing the merge. I'll then be happy to merge it. Thanks for your valuable contributions.

**Comment by sujliu** [comment]
Thank you both. Yeah, I agree with @SiggiSmara that the xml way is better than the regex matching.

**Comment by tmpjr** [comment]
Please open a new pull request when completed. Thanks!

**Pull request closed without merging**
