### PR TITLE
Updated Article.php for pubYear, doi and pii fetching

### PR DESCRIPTION
**Pull request by sujliu**
I have made changes to 3 functions in Article.php:

- getPubYear(). In case JournalIssue/PubDate/Year tag is not present (e.g., PMID 2342890), get the value from MedlineDate. 

- getDoid() and getPii(). Since ELocationID element houses DOIs or PIIs only, and DOIs have certain patterns to match, I used regular expression to determine if the value is for DOI or PII, and fetched them accordingly.

Thanks!

### CODE REVIEW

**Comment by SiggiSmara** [comment]
There is also wearejust's solution to the same problem that has not been pushed to the upstream branch. They look for the ElocationID attribute EIDtype (DOI or PII). I would personally go that way rather than regex mathcing but if it works it works. 
See here for more info:  https://github.com/wearejust/pubmed/

**Comment by tmpjr** [comment]
Thanks to both of you. I'll look over the options and make a decision this weekend.

**Comment by tmpjr** [comment]
Hi @SiggiSmara 
I'm sorry for such a late response. The link you gave for wearejust's solution is no longer working. Please create a pull request for his solution and I'll consider merging it. I don't have much time these days to work on this library but I'll do a better job of checking up on these issues and merging request. Thanks for your interest in this library.

**Comment by SiggiSmara** [comment]
No problem. I guess they abandoned their modifications.  I've closed my previous pull request ( #5 ) and added a new one with both proposed changes.

**Pull request merged**
